package com.isnakebuzz.nicksystem.Utils;

import java.security.SecureRandom;
import java.util.Random;

public class RandomUtils {

    private static String[] Beginning = {"Ael", "Aer", "af", "ah", "am",
            "ama", "an", "ang", "ansr", "cael", "dae", "dho", "eir", "fi",
            "fir", "la", "seh", "sel", "ev", "fis", "hu", "gar", "gil",
            "ka", "kan", "ya", "za", "zy", "mara", "mai", "lue", "ny", "she", "sum", "syl"};

    private static String[] Middle = {"ae", "ael", "melos", "me", "mal",
            "zom", "red", "cra", "ark", "ake", "arc", "miri", "stak", "iz",
            "bee", "bie", "marac", "zoir", "slamar", "salmar", "urak", "", "", "", ""};

    private static String[] End = {"Buzz_", "stack", "craft", "games", "arco", "me", "in", "sn",
            "tron", "med", "ure", "zur", "cred", "mur", "Amyleshie"};

    private static String[] names = {"Aspidetikon", "AttractivePeatear", "Cathyre", "ChiariCyRoll",
            "Compane", "Dakoice", "Dasieredoce", "Dewinvest", "Druisteate", "Ecundpho", "Febrier", "Flawayha",
            "Frachiza", "GreatCutie", "Grounexpl", "Hermente", "Ifallaxis", "Ikleundn", "JadenHelp", "Ladyturnet",
            "Legendergy", "LegendKool", "Notervell", "Paktezio", "PlotWind", "Proxyston", "Psycheterda", "Qualedant",
            "Ravagonic", "Amgenesem", "Bandset", "Battain", "BeachKaptain", "Boroutil", "Broadwayer", "ChicPapa", "CistAdvice",
            "Couralle", "Darynth", "Decelep", "Delightontr", "Doodletelx", "Expredo", "Famickboa", "Fisatuna", "Fluentisen", "ForlifeViking",
            "Gravitychet", "GrundyChee", "Harolisher", "Inkpholo", "Interli", "Jetstepis", "LolaRat", "Metruple", "Nameractoo", "Numeronism",
            "Panettaboom", "RyothTiger", "Aucting", "Barlocant", "Bilenews", "Contech", "Cookielder", "Curalet", "DreamySound", "EatsyouStart",
            "Elliserba", "Ernaripl", "Ezoneti", "Famous2hot", "FlashSound", "Gainewc", "Genterat", "HeavenSell", "Henavast", "Hipurcell", "Hoiredea",
            "Kurooticul", "Lightec", "LipsxHappySaki", "LogicChoose", "Lympultu", "MatterSublime", "Meriston", "Namellon", "Oubakens", "Paperpune",
            "Pedrono", "Allinkfire", "Burntianage", "Cabeden", "Chevlity", "Crossedimac", "CuddlyLog", "Dinpreten", "Elliprozi", "GreyDemon", "Herelski",
            "Hopetendsm", "Inagold", "Insideauct", "IntcatProphecy", "IssClassy", "Jellware", "LawPatty", "Leekharm", "LeonLabs", "Loralsten", "Lucilife",
            "Markinric", "Messagesin", "Monavion", "PattyFaceSpecials", "Phonode", "PleasantKlug", "Prevents", "RelyMine", "Reptilentax", "Andatasi",
            "AttractiveAuthentic", "AuthenticIama", "BeeRap", "Birderca", "Boredmolo", "Breezebank", "Carbolt", "Coalarct", "Consaking", "CoverRosa",
            "Crosenis", "Czarlengan", "Earthosep", "Enferedee", "Exectrafre", "Geodakh", "GlaceSand", "Gurummerin", "Gurushawna", "HoodQuick",
            "Ibingtrom", "Kissezergo", "Laxrsicnet", "MediaSizzlin", "Monsterware", "Morgeson", "MuchTrauma", "Negafcom", "Ookhanyw", "Agionsed",
            "Apokjaw", "BrightThin", "BrilliantEnjoy", "Bulletingo", "CandyCyXx", "ChanMiracle", "Compace", "Creamsoft", "Epickelyne", "Feistyrxia",
            "Greycommag", "Heremel", "Jusekel", "Linenthinat", "MediumCarGrand", "Mellowthie", "MessagePacRodeo", "Mianchot", "Mosellato",
            "Mulantry", "PrestigeRacer", "Propell", "Proseastp", "Puppyheckda", "PurfectChapter", "Rasbance", "SanAllyWeaver", "Servional",
            "SnoopGrundy", "Abshing", "Accelsh", "Allsentet", "Apticste", "Ascengoso", "AttractiveChunky", "Babytecher", "Clikomec", "Coffman",
            "Comitern", "Conkeyer", "Copions", "Desistri", "Gigglysilo", "Gownerdall", "Johartma", "Kingmanea", "Landshide", "Linkindori",
            "Loveriumet", "Mannectm", "Musionan", "Nefitin", "Norbasafi", "Numeroiter", "Pigligh", "PositiveMega", "QueyPoshy", "Raabeersi",
            "Saschtro", "Ahlseme", "AutKing", "Banditecis", "BlogZee", "BuffSimon", "Burgrese", "Cordines", "Cutestefte", "Cyotagerc", "Daclotle",
            "DiaryReady", "Enowahigh", "Evisute", "Fauchpot", "GeniusTwoPong", "Germani", "Gressite", "HearMama", "Heskamo", "Hiproseri",
            "Hyolingla", "Indumply", "Invteler", "Jemadarle", "LeadBill", "Meggiga", "MinyAboutMoff", "Qbasent", "ScreeBlondie", "SingKeeper",
            "Ardeandy", "Beachem", "BinderEdit", "Cationli", "Cismeday", "Clarkin", "CrunchProFred", "Cutieldlink", "DeanPitcher", "Dreamesused",
            "DrummerWill", "Editizonix", "Fortunera", "Groupsour", "Invocap", "Kalizard", "ListQuayle", "Maxonetookl", "MohawkPuppy", "Mosiondoub",
            "Noraumstr", "Nylstra", "Pentaxion", "Rackelat", "RaeMatrixBee", "Reporterhu", "RoachDirty", "RoseJimGrant", "SanGlossyHappy",
            "Slayrotmeni", "Adaxiaen", "Allineop", "Anisoftfa", "BeautyCanyons", "BigForb", "Brairmou", "Briberton", "BullTroik", "Bunnybanges",
            "Carilde", "Dersecia", "Dmarctino", "Donauzen", "FairyWittyBe", "Footballer", "ForlifeCountry", "Guiarapl", "HearUpdate", "Hoplowa",
            "Horrayredi", "JimGolden", "Kixdcapin", "LaughSushy", "LiveInfamous", "LovesYau", "Mastester", "Ospowell", "Poddynamm", "Reportergi",
            "Ricifusi", "2freeSpoon", "Antonen", "Aphydrey", "Birdomance", "Boltiver", "Canfusti", "CanyonsForever", "CarProud", "Deludgear",
            "Demaglela", "EatsFly", "Entopends", "EventsInfamous", "Exiassel", "ExpertSky", "Fleanoffre", "Giftstocc", "Grundyment",
            "Heartumed", "HempUniquePuppy", "Histobyza", "HolyQuick", "Lilynnes", "Lybeamme", "Moundande", "Muniahab", "Parkersona", "Petstage", "Precity",
            "Ravagerid", "Allistrade", "BeachYoung", "Blondeluard", "Boardindipl", "Bozichekh", "Cassout", "Catacell", "Champiquard", "Chempode",
            "Codexel", "CoopsForever", "Coverado", "Crotacom", "Danelle", "Encodge", "Gicoredl", "Groompa", "Heborist", "Homeyward", "IneedMatrix", "Janetsch",
            "Jervinte", "Jungerlava", "Kaiperefi", "Logictaxyen", "Magicidgeny", "MountainToy", "Nentacre", "Pufflelife", "Riceribu", "Asteched", "Babsonix", "Binderango", "Binderoona",
            "Biteker", "Blangent", "Botultron", "Byworksm", "Carrust", "Certionix", "Clearco", "Enwinpole", "Frosyser", "GameTwo", "Gannoli", "Heroxylo",
            "Ideaticom", "Indacomp", "KuroPriceless", "LovenPrecise", "Mannetru", "Myeliplay", "Newslagesp", "Phemarch", "RadioCutie", "Rahroord",
            "Resider", "Rudement", "SandAngelDemon", "Scapedzu", "Baseaude", "Bestecidya", "BoostTricked", "BotPsychVivala", "BoyChrome", "Brainywood",
            "Chiarinete", "Cideplus", "Convint", "Cubesagsm", "DragonRoz", "Eagentek", "Eclogon", "Frankonna", "Frediardyn", "FunDudeGazette",
            "Hinchariu", "Holycommiq", "Incallwood", "InfamousForever", "Ingfield", "IwantCrayon", "Jeansave", "Kryptomari", "Messagesco", "Molliana", "Mowererisda",
            "Ooshoerl", "PhatCrispSra", "ProudGorgeous", "Agnelin", "Bomberdian", "Breedek", "Caesaibus", "Claeroom", "Clawayti",
            "Comtism", "Crealsocm", "DeskChamp", "Djinforest", "Doodlemie", "Enjoynemy", "Execonneww", "GrundyBlue", "Gurionep", "InvaderIte", "Lettersear",
            "Medvales", "Mendityle", "Netwoolut", "Peoplin", "PopularHope", "Radiageli", "Rustanar", "Sharergua", "Showboa", "Sigherze", "Skatisab",
            "SonPsych", "Achatems", "Aeratmacr", "Berettaff", "Biletheo", "BunnyTruckSo", "Burrinde", "CapoPong", "Chacrule", "Cohesmate", "Curales",
            "DiagonalTinker", "Dortuash", "Easylvarma", "Eworksmu", "Firedalock", "Gasiontr", "Intellium", "Islamoh", "KeeperCoverage", "LeventisBuddie",
            "Missiving", "MusicStone", "Openpal", "Personixel", "Portormen", "Posswurt", "Prestee", "Pretivens", "Punchorga", "Rockettech", "Ajinotell", "Avtentr",
            "Beachaetegu", "BobDrWarm", "Cosiagka", "CountryTwitter", "Deptingt", "Digitch", "Dimexhi", "Diverin", "Eatschback", "Forbaktism", "Fordetsh",
            "Freakerer", "Gamerlecing", "Groenza", "Haarest", "Hitelley", "HockeySnowboard", "HottSublime", "Issuester", "Jaquate", "Kiotonets",
            "Mastimil", "MuchGrinder", "Nexatima", "PlaceTrainWin", "PrepBoardBugs", "Scholeve", "SchoolPeak", "Assapolo", "BagoEdgy", "Boardbarb", "BookUpdateInspiring",
            "BootyTactic", "Cloetechs", "Crescentvi", "CrispWubba", "Danworl", "Dulutiba", "Endlopti", "Ferzkori", "Goldclage", "Hartheersa", "Homopcs",
            "Insidayal", "Kurding", "LogicTrevor", "LovesAbout", "Mediumeire", "Mentfxie", "Netafou", "Numerogaus", "Populdstarg", "PrimeForum",
            "Refutorse", "Relaction", "Robbinap", "RonzCyber", "Roxentosavi", "Angeliconap", "Archsin", "Blacklevybl", "Brycent", "BugsEditor", "Calypro",
            "Catpiggio", "ChickGirl", "Coamish", "Cordjyll", "Cownetis", "Coxarcre", "Dravenburn", "Duderoeing", "Eclipri", "Emerlist", "Equorth",
            "Fallencrea", "GossipRecipe", "Hardoccu", "HighLuc", "HyperBauer", "Jamberth", "Knightekab", "KryptoWay", "Lauriumbe",
            "Letraved", "MagazineThere", "Magicettive", "Marketsil", "Arousse", "ArticleIntincr", "Bradunte", "Brittleer", "Cabrincu", "Carrilia", "CasualHeaven",
            "Cleardtoo", "Cookietule", "Deliquat", "DipityTips", "Diverheal", "Esoleria", "Flexprof", "Gamermine", "Gelarism", "Hagseisag",
            "KenkaHehe", "Liferystat", "NicerAngels", "Ostatris", "Phungeni", "Pinchoastas", "Pitchertybe", "Reneweb", "Salismyt", "Salistafi",
            "Shoesthwill", "Silvant", "Sk8rcsents", "Announcercu", "Aritalth", "Caperer", "Coelcope", "CookieZin", "Crazymeland", "DramaPoet", "Dualthad", "Ekairdim",
            "Eviaines", "FlashTracker", "FreexTwistCoverage", "Hottechilic", "Hyposfemi", "IslandScorpion", "Kiddownpl", "Lenkasinc", "Leoniclede", "Logymbie",
            "Medpoint", "Metropr", "Miumedde", "Monagehe", "Nerjient", "Rennaker", "Sealeguid", "SimplyLing", "Sosa2free", "Spinfresig", "Sunsetlydi", "Aintorth",
            "Birgerie", "Blinkinte", "Bolidot", "Bootsto", "Bruelog", "Celplante", "ClownSingShow", "Corpoint", "Cottondope", "Decrence", "Dirtypele", "Djintelevi",
            "Econosons", "Eurocus", "GigglyBorn2", "Grafidder", "Hartlen", "Herlingal", "Inventreof", "Jollystin", "Katreserra", "LaoEyes", "Mahopolig", "Maxuman", "MissingShay",
            "Moloneo", "PleasantMy", "Pressahould", "Scorpiongs", "Advicenter", "Aholicomet", "Avianati", "Bsidgent", "Buyvipla", "Chicerer",
            "ChronosWard", "Coatedge", "Coreamen", "Dataminte", "Derentsc", "Dressynywi", "Dultysda", "Felitero", "Fortelie", "Fraenable", "Fredelissi",
            "Groeite", "Hauxiebo", "Inettawe", "Isotrades", "Ladycyteek", "Latermi", "LolClever", "Lothemis", "Netbarbox", "Netstarks", "Pionerspi",
            "Puddurry", "RapKai", "Addreco", "Aelanley", "Ajouplan", "Alexatres", "AquaticGino", "Berylle", "Bulgerto", "Cephoric", "Chaticomvu", "Cleserli",
            "Coggerpi", "Coulton", "Deixismit", "Emdesbynx", "GigaMudTary", "Greyermedi", "Hennics", "Jeanswishal", "Maniakerer", "Minestad", "Monghape",
            "Nautaxio", "Phoenixia", "Pinaliali", "Primena", "Proacchm", "QuayleLordNumber1", "Respoager", "Ronzientou", "Sadwaysts", "AboutSpecial", "Aceteron",
            "Adoreassi", "AnnonLaw", "Arsenally", "Ballyma", "Blikitter", "Cheesciend", "ChromeDrama", "Coghlumby", "Corphypn", "Coventis", "Cutenetblo",
            "Esiaplow", "FoxPride", "Garnettea", "Genician", "Gigglytera", "Gigunicon", "Graning", "Homeyebra", "Intafabe", "Khadrytedn", "Kryptonken",
            "Lorneorld", "Nightonalry", "Novitsub", "Plancend", "Prankeyesti", "PricelessMom", "Alcolpha", "Antecos", "AuthorChanCampy", "Blightfo", "Cellroma", "ClawChone",
            "Corayco", "Croaker", "CrunchCrayon", "DavShoesPapa", "Deandstobu", "Energynoop", "GameSweet", "Goerveri", "Hirequest", "Infernocu", "Inklerie", "JungHyperClever",
            "KhadDipityWet", "LocalTopics", "Lorantel", "Marketikon", "Mithansn", "Mundemate", "MurphyGodzilla", "Netpowebo", "Oneardrasba", "Partylocamb",
            "Poloima", "Proportem", "A1tprouped", "Aguasse", "Alertergy", "Angleoppr", "BulletinPower", "Caginve", "Chikancent",
            "Clownhabene", "Ditypenn", "Dolilker", "Ectowxch", "FarSand", "Fizzbanket", "GamerFighter", "Hailsoj", "Harionti", "Hoodyenter", "Lawscal", "Logyleco", "Norchin", "Norwinger",
            "Onidati", "Orpsonwa", "Readynard", "RockMiss", "Rounderba", "Scantus", "SeenSkate", "Simultsen", "Sk8rAir", "Abeillian", "Americand", "Bowheadma", "Bvicorma", "CentSoft",
            "Chasecomars", "ChronicleChamp", "Daneorks", "Dollernage", "Dynafen", "Fulnorti", "Gineurce", "GlaceBurntForlife", "GrundyTinker", "GuruLinkin",
            "Hyperans", "Ininspla", "KuroCat", "LuckyParisRob", "Medialmi", "Moolives", "Pacifacom", "Pongtorite", "Preterc", "PuffLabs", "Robodiac",
            "Roosent", "Rosesidgeom", "Sourcean", "Stanbow", "Aircrearr", "Antesynt", "Authentican", "Boudersh", "Boyacleto", "Brierva", "Callist", "Chosensoft",
            "Coharege", "Comptepp", "Coonsick", "Cozymenshi", "DasLand", "Dativers", "Diumusus", "DjMundeSunset", "Fishiron", "Grinderanse", "HoodMatter", "HopeWas",
            "Hulkheetta", "Iconsen", "InteriorVivala", "Islamethr", "Jangidge", "Kinshipli", "Lantella", "Localtron", "MuraDot", "Opritail", "Agdertomm",
            "Amimetco", "Angelicor", "Beachonit", "Bookrantso", "Bytechains", "Cairoco", "Chroniclevi", "Constouc", "Contenticks", "Daunegaia", "DevBoosh",
            "Eliathwi", "Estrust", "ExtraSports", "Figuiste", "HipurPersonal", "Huietype", "JoyKit", "Katrackbat", "Knightergy", "Magnorxia", "Manakonia", "Mazorce",
            "Mesirad", "Newsediaco", "Pagease", "Perfectielo", "Prisbach", "Saindist", "Agelogra", "Annition", "Beartivisi", "Biolveaw", "BreakingCrayon",
            "Champli", "Dancensmort", "Deskoluter", "Diary2cool", "DictatorSunny", "Eximalth", "FunGodzilla", "GeniusEssence", "Globerxi", "Goofyrekaye",
            "Govider", "Granderma", "HoodInca", "Instamble", "Jubberco", "Junkyhard", "Keripelt", "Lacossbla", "LilVirtuoso", "Margiann", "MessageYellow",
            "Moultarg", "Powerli", "Prankeronna", "PressChosen", "Abolink", "Achevolv", "Allingtota", "Altenneg", "Ancilli", "Armobian", "Bargaterr", "ChunkyWar",
            "Compostat", "CrossedThenorn", "Delhirect", "Doffelle", "Erosisup", "FaithSlipk", "Famoustren", "GuitaristFor", "Headseldo", "HotJuz", "Kabrecon",
            "KaptainWonder", "Pilogyny", "ProActive", "Refedbot", "RozComfyKurisu", "Ryothercand", "RyothStarChiquita", "Simpleu", "Solulona", "Stlityjo", "Studiumin",
            "Antwegior", "Aquaticer", "Britzer", "Classyncie", "Clearclus", "Daystabuff", "DragonAsh", "EatMessages", "Efionate", "Enviset", "Eywoodin", "Foxfiball",
            "Grassionb", "Haumerra", "Heckfier", "Issuedust", "Jarldwi", "Leolistom", "Lorgergi", "Marlest", "Metraxer", "Moolvea", "NoticeBlonde", "Orbiteder",
            "Paelexce", "Parlinno", "PonyAware", "Rayconom", "Reptilequ", "Sadyese", "Amatasm", "Apenguinta", "AwareDeep", "Blackenerce", "Blinksone",
            "BomberBurnt", "BroadcastScan", "Crinomi", "Cuteraline", "Denderna", "FreshChiari", "Frogeover", "GoobleIsland", "Gundeship", "Jinnionry", "Macredia",
            "MaidLogic", "Miserwa", "Neomeran", "Newsqwa", "Openatrac", "Pliernati", "Pluscipipe", "Prelawner", "Racingfoto", "Sagaylli", "ShcamRee",
            "Shederli", "Sisterthey", "Sonospath", "Admindra", "Alespens", "AngurisGenius", "Brassie", "Burntemia", "Campanti", "CandyCozy", "Chansph", "ChiPrecise",
            "Choneurcell", "DasFlirty", "Datassafe", "Draymisio", "Ektradvi", "Epitomo", "Flophil", "Frastriq", "GambitRadio", "Gentisla", "GoldVibrant", "Granurit",
            "GreenActive", "Homemanki", "Immucham", "Jordueli", "Kronateas", "Lewdnes", "Listinsure", "Logicalix", "Murphem", "Advanem", "AnnouncerStasia", "Arsenalli",
            "Billionet", "BradelUpper", "Casallu", "CeticChiquita", "Commentser", "Cooffice", "Cyrespri", "Detrola", "FinalDas", "Footwit", "Fotorper",
            "Generge", "Getfronewer", "Golderpa", "Inspiringst", "Ioleasub", "Ipreous", "Jocketro", "Lectooke", "LordYounger", "Mamarjoyer", "Medityli", "Newskincal",
            "Niecome", "Pleasanthr", "Plentyrano", "Quickag", "Adamset", "Bananneop", "BiggExec", "Billionsu", "BuffTiger", "Clarbrou", "Conical", "Dailyconv",
            "Datataro", "Discoverma", "Dixielddi", "DubyaBig", "FerdyBuddie", "FleaContent", "Glerlect", "Godhopple", "Guantorkka", "IceMaid", "Incalessee", "Intysewo", "Lamicasa",
            "Laughtyan", "Masonic", "Moretein", "Mundesatech", "ParisBillion", "PartyStone", "PierceNumGlimmer", "Privanc", "Prolinsom", "Articletozo",
            "Ballist", "Beastroadri", "BWithalis", "Charionly", "Chooseedia", "Dailysanten", "Datangle", "Datstream", "DiagonalBillion", "Drawayne", "FreeIss",
            "Freyepri", "Germarcer", "Hulkweedia", "Ineauxie", "Isersang", "Kutzithk", "LifeSk8r", "Lindelk", "Mairenali", "Mitzmada", "NarrativePriceless",
            "Neftmark", "Personthee", "Podanseal", "Pubioseb", "Ravenauto", "Rebarwat", "Ronedary", "Agarigh", "Bamberg", "Basissi", "Bergoffi",
            "BoardPoet", "BristleGenius", "CanyonsTrust", "Chooseduc", "CoverageSon", "CrescentLoven", "DiscoverSoccer", "DreamWinCrown", "Elizaha", "FallenBleak",
            "Inspireater", "IteWasabi", "Linededit", "Mabuction", "Noggies", "Ovexcert", "QuayleDigy", "Ragelink", "RavagerAlly", "Sadolis", "Schsreet",
            "SeeTiger", "SimplyFred", "SmgBrace", "Spitonet", "Spritogr", "Absoftth", "Acbelit", "Acreysik", "Androta", "BootScorpion", "Buffymentel",
            "BuggyGreeShadow", "Copereen", "Crossedimer", "DariSkier", "DavRing", "Deskilah", "Duumunci", "FateCookie", "Forumakon", "ForumInsider",
            "HartZine", "Headerry", "HipurBuddyTheevil", "Holendbe", "Imotecti", "Interint", "InvaderConfident", "Kallerst", "Katrenuest", "Laurelsy", "Marensh", "Mcenself",
            "Missinvat", "PeatearCasual", "AmericaTreasure", "Amsangeoi", "Blowerbl", "BlueNephew", "BoxCrispAttractive", "BoyDonald", "Brilliantet",
            "Cessari", "Chikkahid", "ChiriShark", "FarSpyder", "Followinez", "FootballTwit", "GurlSan", "Joursilk", "LeakLinkDreamy", "LingChiari",
            "Maxbitekris", "MellowHelp", "Nybolonen", "Paperpose", "Procell", "Rementor", "ReporterThin", "ShabbyBloom", "ShatGreen",
            "Sheedome", "Smarterat", "Specialtemi", "Spection", "Accreen", "BalBabeTrite", "Bridthou", "Cafemon", "Compuliz", "Culerayt", "Editatonic",
            "Emington", "FortuneRaven", "FreexStar", "FriendCharms", "GiveLogVengeance", "Hartnester", "Huskerbi", "Interestar", "Katyaskag", "Kiontval", "KittyWaves",
            "LimeTwoZap", "Megaiative", "MegaVampire", "Mithieda", "Musickabi", "Nashuma", "Norstonta", "Playfinaul", "Rosalingar", "Semonixia", "Simondioner",
            "Slayerisom", "Acindsp", "Afterio", "Barnephob", "Bracellup", "Brevinman", "Corealth", "Crcaotern", "Crunchoswa", "CuriousGravity", "Diddynameta",
            "Digeoutia", "FarBalByte", "Frasisen", "Furtentu", "Helmint", "HempHappy", "Isocroakl", "Kathregi", "Kixndlowo", "Leadlibelg",
            "Linector", "Longbro", "Mansperubi", "Migrada", "Nearlytill", "Netiones", "NetworkGlace", "Nocomet", "OmahaMyWise", "Predgeli", "Abactime",
            "AttractiveKissez", "Barrusca", "BasePanet", "CheerupGod", "CheeZoom", "ChilledFrog", "Commenten", "Cutbanced", "DevSister", "Doughli", "Gnomedweber",
            "Heterta", "Hypekita", "HyperStories", "Idealoteo", "InspiringSpuffy", "IssueChan", "Italeli", "Jacksacr", "KeeperBeach", "Kisseziana", "Literlo",
            "Lometask", "Lovehoters", "LovesInlove", "Manician", "Nearlynnoy", "Nozymentli", "Numerheyeme", "AholicXan", "Amicalin", "Bigadela", "BoboConfident",
            "BreezeDj", "Buschere", "Cajaddes", "Chisioxi", "ClawWonder", "Cockiety", "Comartron", "Daggate", "Enaerady",
            "Firessou", "Formult", "Fujiter", "Giscrich", "GoldenTinker", "Humcoveri", "Idlerge", "Kellerse", "Larraphor", "Mastreca", "Medcevi",
            "Megsunsall", "Oleancery", "Phiantield", "Rejecon", "Scorpay", "Sheltifyi", "2freenetp", "Arizone", "Baskuale", "Blinkergift", "Brascumbn", "Byggeria",
            "Chellaria", "Chugherit", "CoolComment", "Counthoge", "Cutechemic", "DaySummerNicer", "Duckbox", "FearQuick", "Fourcentag", "Groverer", "Hunderia",
            "Icyaxisos", "IffyVikings", "Inchgent", "Interview", "Madertonym", "Mohawkeyde", "Mousecutl", "NarrativePlot", "Redected", "Relifemi", "Ringernary",
            "Saxorati", "Shinigr", "Appolisto", "Appsevel", "BoxRoll", "Bullderia", "Certean", "Clemelime", "Compainet", "Cyberonli", "DigyWeaverChosen",
            "Ellerypt", "Funkyladyne", "Givellergy", "Healturce", "Hindsmi", "Inasoftpa", "IsGold", "Jrgettersi", "Keukatics", "KroolLaoThedevil", "Luxuseuer",
            "Mantaners", "MatrixFeisty", "Mccluso", "Outfletum", "Partivest", "Racerbern", "Relaxarcaja", "RiderMew", "Ripployds", "ShortFlavored", "Bancrima",
            "BillionHeaven", "Bombali", "Castereq", "Coschrid", "Cranitele", "DariGigglyGinger", "Dativehi", "Digesenti", "Fitneyfl", "Fraenditi",
            "Ginolarkom", "GrundyCert", "Herijour", "Hightechee", "IamaPhobic", "Ieuroleth", "Intincron", "Isererso", "JinWaterFestive", "Kinogyrera",
            "BeastBill", "Lingraff", "Mistento", "NarrativeStasia", "Nexfibe", "Partive", "Poreengl", "Pyrexormx", "RaeDigy", "Reconterf", "Accrereti", "Anderoned",
            "Berwriga", "Bestingeno", "Birdenry", "Cestarke", "Citriscom", "CottonBizarre", "DaysSushy", "Delnergy", "Ectsence", "Fluidgert", "Fredgentap",
            "Freemcman", "Hicklis", "HockeyCooled", "Hydresis", "Kildatarm", "Listrealth", "LolaA1", "Monerer", "Ontraines", "PatFestive", "Preciseig",
            "Questem", "Republe", "Snapoint", "SteveMatter", "TeenageGood", "Armylosi", "Broomaxer", "Chromereak", "Clificro", "Coalionic",
            "DirtyZest", "Dubyardimed", "Flaglow", "FlashJaden", "HanLittleSpice", "HearMafiaFinest", "Heartenslet", "HenryMud", "Hostryla", "Izimicroc", "Jumbure",
            "Luncherer", "Majereales", "Mansondial", "Maxiongert", "Morroonne", "Nteland", "Pestbond", "PhreekXbox", "Quaylenije", "Rappatteroo", "Rodavoli",
            "SilverDas", "Simoner", "SlimCake", "Abelfast", "Ancerick", "Anneontr", "Bageneti", "Bashboil", "Biowitt", "BornZine", "Breakingiu", "Chunkyphil",
            "Confrette", "Danieldal", "Deanoverer", "Dogcaloor", "Doraptio", "Gomullam", "Harinews", "HeadlinesGodzilla", "HelpfulFallen", "HiBobo",
            "Hinchesista", "Ioniderat", "KaptainParis", "Kemasqua", "Kovsonwi", "Metarin", "Playindahl", "Queyetryto", "Quickuponey", "Relaxceptru", "Rollerrian",
            "2coolSantaJo", "Abuttle", "AraSeenLink", "Arleging", "Bleaknewfin", "BuddieSpot", "Cataparie", "Centimanc", "Cilineoc", "Coulabax", "Cownshel",
            "DoggHemp", "Enertnett", "Evnakato", "Feigene", "Finalche", "Givertbuny", "HighGazer", "Hyallect", "Katlemu", "Laughounder", "Liketechfx",
            "ListTeenie", "Malishing", "Narrativell", "Neillunger", "Nekollvity", "Neupata", "Pendelly", "Protropy", "Ackerixio", "Addrelyhe",
            "Adialsbe", "Ancyrkey", "Bergallow", "BlabFunk", "Burghtben", "Calamitor", "Carrother", "Chercove", "Classystem", "Commentstr", "Costatyr",
            "Crossediain", "Devellere", "Earforoo", "Ermassale", "Exoticaler", "Footcheri", "FunnyKeeper", "Heallyte", "Infrogue", "InteriorThin", "KaptainDraven",
            "KryptoCrunch", "LucyFix", "Newswellho", "NoticeBristle", "Pectortu", "Pleasantro", "Addexpo", "Altewick", "Apinuest", "Boardence", "Bornheihe", "Brinfoce",
            "Capetrue", "Chicuemaro", "Chikonfeat", "Collanati", "Cotterio", "Coventeg", "CzarBeauty", "Diarynealis", "Dingenst", "DjMr", "Epocrot", "Fanleware",
            "Fantasyst", "Godzillari", "Lettion", "Manetkyr", "Maryaleuc", "MyFly", "OnlineSmart", "Pellahome", "PenguinRavager", "Peoplysse", "Pitchersg", "ReadNumber1",
            "Blackenna", "Bluedeckle", "BoaKit", "Bootexparm", "Chairewor", "Chockman", "Clawayines", "DigySo", "Discovergy", "Dollibleen", "Edeletro", "Electrim",
            "Fairedia", "Fibrect", "FlashyGolden", "Fusitegr", "GameMiracle", "Graditism", "Invoiceb", "Leaguiler", "Legendmarc", "MyTreasure", "Natingue",
            "Norittee", "Pascarlia", "Pointear", "RacerVod", "Reportshe", "Safflun", "Sfieress", "Accetitar", "Aforkson", "Alogensu", "Anabackta", "Battermo",
            "Bresledge", "Charineli", "Colarcom", "Commerra", "Crossedia", "Dreyllan", "ElementBeach", "Entelogal", "Fibeuman", "GotSlayrFour", "Hotgica", "Ilattrav", "Islandomot",
            "Joicell", "LedgerExotic", "Linkaposte", "LolBloom", "Mannetvia", "Melector", "MercyAce", "Mindrade", "Mobergon", "Neileeplig", "Nexlink", "Partsys", "Anodevo",
            "Assesyn", "Blintems", "Buggenano", "Cubianci", "Downiari", "Dysphab", "Flagstley", "Footballer", "Headlinetx", "Hesserie", "JameGato", "Jidefathel", "Laksappan",
            "Leenedra", "Logynymo", "Mainflex", "Maracolls", "Mediplex", "Melcrafreux", "Meleneow", "Mogossay", "MotoGetCookie", "MuchLime", "Narcreli", "Necticer", "Obletech",
            "Quickermint", "Razugaiana", "Realearet", "Anenixty", "Angelschst", "Articleswh", "Awaybilkie", "Beliceltron", "Binoutio", "Bloggerag", "BradelBlink", "Castgram",
            "CookyGame", "Euernetf", "Fawcaphi", "Frucance", "Gangtari", "Genumenh", "Gossipoiko", "Grouponal", "Grouporse", "Impextr", "Jataand", "JournalNotice", "Liesbase",
            "Manseyorat", "Mansurcess", "Megardaryt", "Pepsalla", "Portman", "PrepWeirdTools", "Pureamedic", "ScaryZerp", "Aboventia", "Acteboxal",
            "Alpipenc", "Angelstola", "AnimeCent", "Apparke", "Beambodi", "CanyonsSis", "CasualMiny", "Chemage", "Curesall", "Curicsup", "Easseene", "Emedgend", "Equitat", "Firstodleco", "InloveBubble",
            "Issuildfa", "KentrosRead", "LatinaBaby", "Lonnavert", "Morageno", "MotoUrRip", "NoticeOlympic", "Parcomman",
            "Phillet", "Portarmed", "PunkWarPower", "RavenNicer", "Royalkalm", "2cutecher", "Borderty", "Bubblected", "Chosentrie", "Chrosite",
            "Clerket", "CookieNaybor", "Cyberix", "CyStories", "Diagonalte", "Dingergy", "Dreamensoft", "Elincel", "Enketski", "Entelspen", "Facermange",
            "Feederin", "Hitflue", "Horxiajo", "InteriorLao", "Kafkantal", "Kidwerasy", "Liberinsi", "Litelege", "Mortiana", "PhoenixReePeach", "PsychPeakTinnys",
            "Secluffer", "ShmoeWorldRelax", "Sillydipo", "Aftermi", "Alogence", "Apriliaen", "Astrolvi", "Bloggerer", "Cheredna", "Coorceni", "DeluxeFace",
            "Duercine", "Fangrylife", "Gelinect", "Grievergy", "Hagionsac", "Hyperlandem", "Insator", "Insindi", "Invaderer", "Kentrossi", "Lawnertine", "Lilligynarc",
            "Luredtou", "Mamatraini", "Mapledy", "Mindmalink", "Neryolor", "NoteExec", "Oneeither", "Otrocing", "Palisma", "Promenvi", "Agonkonn", "Allerim",
            "Becketsuno", "Bonestone", "BristlePool", "CakePinch", "Calanwear", "Complor", "Cygatech", "DasBago", "Dishthead", "EliteZippoRainbow", "FanSummerMusic",
            "FantasyReal", "FleaPapaXglossy", "Freakerie", "Gopakos", "Headlinesta", "Invadersc", "IssueIce", "JollyChikkTweet", "KnightAudience", "Laseral",
            "LaughFinest", "Luabochi", "MintDay", "Nestyreu", "Partionny", "Persecta", "Recipecize", "Ajasach", "Ammasaron", "Epigoet",
            "Aphytech", "Blikindan", "Borsagent", "Bratrox", "Coludext", "CornyCent", "CrispDude", "Crossedinde", "Dealexec", "Diacher", "Eingerop",
            "Finicson", "GoodMonkey", "HomeyPleasant", "Kiddoraylor", "Laiciba", "Lilachent", "LyfeLeventis", "Nofferer", "Oridist", "PatMore", "Picisla",
            "Piergyny", "Placellowsl", "PsychMomLady", "Puffentiop", "Ronicsup", "Aftencend", "AirThebestPac", "Ammotiva", "BabixzDaily", "Bilecuest", "Boardines",
            "BuffyTipsSushy", "Cableonal", "CakeExpert", "CarChikk", "Cornympon", "CraziiRecipe", "Datapsemi", "Dortecen", "Evercentee", "FreeWitchSocial",
            "FuzzyAngelic", "Gruntrine", "Hemmeryw", "Invergy", "Kitchmark", "Lexiate", "Lunchaira", "Mashbore", "Minyelable", "Monikrealee", "Murackyalt",
            "Oktobje", "Oxaltory", "ParkBlacken", "Aderlate", "Arsenalds", "Bearentala", "Betatuma", "Bootillaim", "Bureseid", "ChickBall", "Chiffer",
            "Coolife", "Crownesolut", "Dragoutte", "Earthmyop", "Eltekni", "Exoticeota", "Factsacto", "Freedount", "GeniusGossip", "GetKissezChirp",
            "Gooduceuri", "GorgeousSchool", "Grosalys", "Hecklaim", "Ingsoeck", "Iradeal", "Jakksto", "Katzelia", "Kscatcap", "Neveriefy", "Overonon",
            "Ratiott", "BeatDot", "Bitamblooka", "Bobomanica", "BootySno", "BurkeTwit", "Chempor", "Coordura", "Corrimpa", "Cumerama", "Cutievela",
            "Dcovishi", "Deniton", "Diddytvoi", "Dierban", "DiscoverBlue", "Firstoni", "FlashBlacken", "Greyecture", "GuantoNeil", "Hanaimin",
            "Kizzeech", "LucKitty", "Macelebi", "Maticsup", "MidnightActive", "ActuallyScan", "Advicenthe", "Asblenix", "Bambellys", "BigLead", "Bleakadir",
            "BradleyMedium", "Brasfibra", "Buglimed", "Chcouter", "Chickerus", "ChronoMaxi", "Comperry", "Corerdon", "Cutbagw", "Euromacle", "Exyserlo",
            "Fantasticum", "Forlifendmi", "Hallwor", "Headlines", "IamJean", "Indiskir", "KurisuMew", "Linklett", "Nawable", "Occamgu", "PersonalSkater",
            "Hannahanie", "Hestervi", "Humaniapo", "Innovasia", "Inureyata", "Playlitoi", "Playworpi"};

    private static Random rand = new Random();
    private static String[] ranks = {"VIP", "VIP+", "VIP++"};

    public static String generateName() {
        return names[new SecureRandom().nextInt(names.length)];
    }

    public static String generateRandomRank() {
        return ranks[rand.nextInt(ranks.length)];
    }

}
